services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"

  ecommerce-api:
    build:
      context: ./ecommerce-api
      dockerfile: Dockerfile
    container_name: ecommerce-api
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server

  banking-api:
    build:
      context: ./banking-api
      dockerfile: Dockerfile
    container_name: banking-api
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server

  delivery-api:
    build:
      context: ./delivery-api
      dockerfile: Dockerfile
    container_name: delivery-api
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
