version: '3.8'

services:
  eureka-server:
    build: ./eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - mongodb
    networks:
      - app-net

  ecommerce:
    build: ./ecommerce
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mongodb
      - kafka
    networks:
      - app-net

  banking:
    build: ./banking
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - mongodb
    networks:
      - app-net

  delivery:
    build: ./delivery
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - kafka
      - mongodb
    networks:
      - app-net

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    networks:
      - app-net

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - app-net

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
